### ISSUE TITLE
Punctuation messes up formatting

### ISSUE THREAD

**Issue by saadq** [blockmar/slackdown#2]
This works:

```js
slackdown.parse('Hey *John* how are you?')
```

Output:

```html
Hey <strong>John</strong> how are you?
```

---

This doesn't:

```js
slackdown.parse('Hey *John*, how are you?')
```

Output:

```html
Hey *John*, how are you?
```

It seems that some punctuation after `*` or `_` etc will mess up the formatting. 

Not sure if you are still interested in maintaining this package though, just wanted to report it.

**Comment by blockmar** [comment]
Thanks, will give it a quick look.
